// Fetch the TurnoGol brand fonts (Inter / Archivo / Sora) from Google Fonts as
// self-hosted woff2 (latin subset — covers Spanish accents) and write a local
// @font-face stylesheet. Re-runnable; cfg.extraFonts points at the output.
//
//   node .design-sync/fetch-fonts.mjs
//
// Output: .design-sync/fonts/*.woff2 + .design-sync/fonts/fonts.css

import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const OUT = resolve(process.cwd(), '.design-sync/fonts')
mkdirSync(OUT, { recursive: true })

// Chrome UA → Google serves woff2. One CSS request covers every family/weight.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'
const cssUrl =
  'https://fonts.googleapis.com/css2?' +
  'family=Inter:wght@400;500;600;700&' +
  'family=Archivo:ital,wght@0,600;0,700;0,900;1,900&' +
  'family=Sora:wght@400;600;700&display=swap'

const res = await fetch(cssUrl, { headers: { 'User-Agent': UA } })
if (!res.ok) throw new Error(`Google Fonts CSS fetch failed: ${res.status}`)
const css = await res.text()

// Split into "/* subset */ @font-face { … }" units; keep only latin.
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)]
const faces = []
let n = 0
for (const [, subset, block] of blocks) {
  if (subset !== 'latin') continue
  const fam = /font-family:\s*'([^']+)'/.exec(block)?.[1]
  const weight = /font-weight:\s*(\d+)/.exec(block)?.[1] ?? '400'
  const style = /font-style:\s*(\w+)/.exec(block)?.[1] ?? 'normal'
  const url = /src:\s*url\(([^)]+)\)/.exec(block)?.[1]
  if (!fam || !url) continue
  const file = `${fam}-${weight}${style === 'italic' ? '-italic' : ''}.woff2`
  const bin = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!bin.ok) throw new Error(`font download failed (${bin.status}): ${url}`)
  writeFileSync(resolve(OUT, file), Buffer.from(await bin.arrayBuffer()))
  faces.push(
    `@font-face {\n  font-family: '${fam}';\n  font-style: ${style};\n  font-weight: ${weight};\n  font-display: swap;\n  src: url('./${file}') format('woff2');\n}`,
  )
  n++
  console.error(`  ↓ ${file}`)
}

writeFileSync(
  resolve(OUT, 'fonts.css'),
  `/* TurnoGol brand fonts — self-hosted from Google Fonts (latin). Generated by fetch-fonts.mjs. */\n${faces.join('\n\n')}\n`,
)
console.error(`✓ ${n} woff2 + fonts.css → .design-sync/fonts/`)
